version: '3.9'
services:
  inventory_service_data:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_service_db
      MYSQL_USER: mamadou
      MYSQL_PASSWORD: Passer@123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  inventory_service_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development

    depends_on:
      - inventory_service_data
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://inventory_service_data:3306/inventory_service_db?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      spring.jpa.hibernate.ddl-auto" : create
volumes:
  db-data:
